# golangci-lint configuration for fasthog
# Based on best practices from bordenet/codebase-reviewer
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
