# Codecov configuration for fasthog
# Based on best practices from bordenet/codebase-reviewer

coverage:
  status:
    project:
      default:
        target: 65%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error

  ignore:
    - "test/"
    - "**/*_test.go"
    - "**/test_*.go"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: true

